### ISSUE TITLE
NHS Bundle Id ok with IOS Simulator on OSX - bit fails to build for real iOS device 

### ISSUE THREAD

**Issue by Kreid4** [nhsx/COVID-19-app-iOS-BETA#17]
Hello I am new to GitHub and Xcode.
I have managed to load and run the NHS tacker app via an IoS simulator on my mac book pro.
However when I try to port the App to my iPhone or iPad the build fails with these errors:

Failed to register bundle identifier. The app identifier "uk.nhs.nhsx.sonar.internal" cannot be registered to your development team because it is not available. Change your bundle identifier to a unique string to try again.

Provisioning profile "iOS Team Provisioning Profile: *" doesn't include the aps-environment entitlement.

No profiles for 'uk.nhs.nhsx.sonar.internal' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'uk.nhs.nhsx.sonar.internal'. 

I am sorry if this the wrong place to ask this question but does anybody have a potential solution please.
Thank you
Regards
Ken

**Comment by Kreid4** [comment]
Worked it out now - change the bundle ID to unique name.
Working on my iPhone now

**Comment by Kreid4** [comment]
Hello next problem for is how to do this.

"Fill in the Environment.swift file with the appropriate values from another developer"

I have an Apple developer account but have nte really used until now.  
I would like to to how to obtain UUID etc please
Thank you
Ken

**Comment by Kreid4** [comment]
I managed to get UUID from this link.  []https://www.uuidgenerator.net
The App installed on my iPhone ok -  but reports "App setup failed"  

Do I need an API number?

**Comment by sam-nhsx** [comment]
Hi @Kreid4 – Unfortunately we’re not providing external developer access to our test environment, or to test against the live environments, so we can’t share this. The app will run without this working, but naturally will flag a failure in set-up.
