### ISSUE TITLE
How to get values for Environment.swift

### ISSUE THREAD

**Issue by dammy1984** [nhsx/COVID-19-app-iOS-BETA#19]
What exactly the values for below ones.

    static let appCenterKey = "an-api-key"
    static let sonarHeaderValue = "a-header-value"
    static let sonarServiceUUID = CBUUID(string: "an-uuid")
    static let sonarIdCharacteristicUUID = CBUUID(string: "another-uuid")
    static let keepaliveCharacteristicUUID = CBUUID(string: "yet-another-uuid")

    
    static let debug: Debug? = Debug(
        registrationId: "an-uuid",
        registrationSecretKey: "a-base46-secret-key",
        registrationBroadcastRotationKey: "a-base64-broadcast-rotation-key"
    )

**Comment by Kreid4** [comment]
Yes I have the same questions. You can generate uuid here https://www.uuidgenerator.net
Not sure about the other values -  I think you just need unique values in the correct format.  So far i have just changed the uuid and the App seems to build in Xcode  and run on my iPhone.  But I am not sure if a do need to change the other values.

**Comment by dammy1984** [comment]
With these values it is working fine. But getting App Setup Failed. 

static let apiEndpoint = "https://sonar.example.com"
    static let appCenterKey = "a992014e-7197-4e5e-971e-778fbb1748dd"//"an-api-key"
    static let sonarHeaderValue = "a-header-value"
    static let sonarServiceUUID = CBUUID(string: "26f4258e-91d1-11ea-bb37-0242ac130002")//CBUUID(string: "an-uuid")
    static let sonarIdCharacteristicUUID = CBUUID(string: "381a1b98-91d1-11ea-bb37-0242ac130002")//CBUUID(string: "another-uuid")
    static let keepaliveCharacteristicUUID = CBUUID(string: "4112d960-91d1-11ea-bb37-0242ac130002")//CBUUID(string: "yet-another-uuid")

    
    static let debug: Debug? = Debug(
        registrationId: "26f4258e-91d1-11ea-bb37-0242ac130002",//"an-uuid",
        registrationSecretKey: "QmFzYXZhcmFq",//"a-base46-secret-key",
        registrationBroadcastRotationKey: "TWFuYXNh"//"a-base64-broadcast-rotation-key"
    )

**Comment by Kreid4** [comment]
same here App SetupFailed 
I am not sure what value static apiEndpoint should be. Any answer welcome
The App is available on the IOS App store.  I am not sure if that App fails?

**Comment by tim-nhsx** [comment]
Unfortunately we’re not providing external developer access to our test environment, or to test against the live environments, so we can’t share this. The app will run without this working, but naturally will flag a failure in set-up.

**Comment by edent** [comment]
I'm pasting this message in every active GitHub issue, so you may receive duplicate notifications.

Today, I'm happy to announce that NHSX has released the full git commit history for the Isle of Wight Beta apps.

* Android - https://github.com/nhsx/COVID-19-app-Android-BETA
* iOS - https://github.com/nhsx/COVID-19-app-iOS-BETA

As discussed, we have redacted API keys, sensitive domain names, and some of the developers' personal details. I am still waiting on final approval to publish the server-side code.

I would like to personally thank the community for your comments, bug reports, and vulnerability disclosures. They all went into helping the development process.

The beta trial of this app has now ended and we've moved to the next phase of app development. It is our intention to publish the source code of future apps as the binaries are released to the public.

Once again, thank you for being part of this.

Terence Eden
Head of Open Technology - NHSX
