### ISSUE TITLE
App set up failed. Retry

### ISSUE THREAD

**Issue by Kreid4** [nhsx/COVID-19-app-iOS-BETA#23]
Hello I am trying to understand this statement

There are currently a couple of ways to do development with remote notifications:

./bin/pu.sh is a script forked from pu.sh. There are instructions there for obtaining credentials from an Apple Developer account. However, we are out of available APN keys, so you'll need to obtain that from another developer. Run the script with the path to one of the example notifications to send a remote notification through Apple: ./bin/pu.sh "Example Notifications/2_potential_diagnosis.apns. You will also need to set the following environment variables to configure the script:
TEAMID
KEYID
SECRET - the fully expanded path to the .p8 key.
BUNDLEID
DEVICETOKEN - retrieved from the console when running the application

I have found all the relevant values except for DEVICETOKEN - how do i find this please?

When do I run the pu.sh script and what does it do.  

Otherwise I can build and run the app on my iPhone and iPad.  However i am informed that the "App setup failed"  
Does anybody have any comments on the above please? 
Thank you
Ken

**Comment by lukeredpath** [comment]
For all intents and purposes there's no way to run the app properly as we don't have access to the server. Once the server code is available we might be able to set up a test server to run against.

**Comment by Kreid4** [comment]
Thank you - I have now found the text in the code and  it indicates a registration failure.

**Comment by Kreid4** [comment]
I am still not sure what pu.sh does and when do use it.   When  i do use it often fails with BadDeviceToken.

**Comment by lukeredpath** [comment]
As I said there’s no way to really get the app working properly right now. I was able to bypass the registration stuff enough to test the Bluetooth behaviour but that’s about it. We will need a test instance of the server, a Firebase account and instructions for configuring the app to use a test server.

**Comment by edent** [comment]
I'm pasting this message in every active GitHub issue, so you may receive duplicate notifications.

Today, I'm happy to announce that NHSX has released the full git commit history for the Isle of Wight Beta apps.

* Android - https://github.com/nhsx/COVID-19-app-Android-BETA
* iOS - https://github.com/nhsx/COVID-19-app-iOS-BETA

As discussed, we have redacted API keys, sensitive domain names, and some of the developers' personal details. I am still waiting on final approval to publish the server-side code.

I would like to personally thank the community for your comments, bug reports, and vulnerability disclosures. They all went into helping the development process.

The beta trial of this app has now ended and we've moved to the next phase of app development. It is our intention to publish the source code of future apps as the binaries are released to the public.

Once again, thank you for being part of this.

Terence Eden
Head of Open Technology - NHSX
