### ISSUE TITLE
was an army base a suitable test environment

### ISSUE THREAD

**Issue by molorosh** [nhsx/COVID-19-app-iOS-BETA#24]
I wonder whether strolling around an army base offers a realistic test of the RSSI distance measurement issues that will be encountered in the civilian work/shopping environment  

Did you also test by having subjects walking around an actual supermarket?  Office and Supermarket buildings are very often constructed in a cage-like structure, with lots of steel beams and supports, and offer very different Faraday cage effects to a purely brick-built home structure (or army barrack).

**Comment by hithomasmorelli** [comment]
I assume that's why they're carrying out the beta test on the Isle of Wight

**Comment by HeadBoffin** [comment]
Or an RAF base, like they actually used ...

The parameters of a live field test of a multi-variant situation is to set hypothesis, run a test under observed conditions and compare the predicted vs the actual results. This is the basis of the scientific method.

"RAFX set up a scenario which simulated people’s experience of shopping. To adhere to social-distancing rules, phones were placed on tables to simulate people clustering in a shopping area. Others walked past as if looking in shop windows."
https://www.raf.mod.uk/news/articles/rafs-digital-airbase-tests-covid-19-tracking-app/

Many armed forces barrack buildings post-war are steel beamed with brick (having slept in plenty myself) but if you are all inside the faraday cage, this is a non-issue. This was just one part of the testing.

**Comment by edent** [comment]
Great question. You can read all about the test at the RAF base at https://github.com/nhsx/COVID-19-app-Documentation-BETA/blob/master/Beta%20Test%20Staged%20Exercise.pdf
