### ISSUE TITLE
Blocks iOS devices ability to connect to other bluetooth devices

### ISSUE THREAD

**Issue by bmacrow-av** [nhsx/COVID-19-app-iOS-BETA#26]
**Describe the bug**
When the app is installed, but not in the foreground, the iOS device cannot connect to certain bluetooth devices at all and cannot connect to others without turning the bluetooth stack off and on again 
**To Reproduce**
Steps to reproduce the behaviour:
1. Install NHS CoVID app
2. Make first run
3. leave bluetooth enabled
4. device will not connect to RENPHO Smart scales at all
5. device will not connect to fitbit devices without turning bluetooth off and on again
6. only permanent fix is to uninstall NHS app, at which point all functionality returns to normal.

**Expected behaviour**
NHS CoVid App should not affect the devices ability to connect to other bluetooth devices.

**Smartphone (please complete the following information):**
- Device: iPhone Xr
 - OS: iOS
 - Version 13.4.1
 - Modem Firmware: 2.05.13

**Additional context**
Inability to connect to pre existing devices will cause user frustration and lead to uninstallation from device, hampering ongoing tracking efforts.

**Comment by edent** [comment]
Thanks for the detailed report, Ben. We'll look into it.

**Comment by Kreid4** [comment]
My Sony Bluetooth headphones connect ok with the NHSX app running.
iphone SE (1st Gen  IOS 13.4.1)

**Comment by Kreid4** [comment]
modem formware 9.52.01

**Comment by edent** [comment]
I'm pasting this message in every active GitHub issue, so you may receive duplicate notifications.

Today, I'm happy to announce that NHSX has released the full git commit history for the Isle of Wight Beta apps.

* Android - https://github.com/nhsx/COVID-19-app-Android-BETA
* iOS - https://github.com/nhsx/COVID-19-app-iOS-BETA

As discussed, we have redacted API keys, sensitive domain names, and some of the developers' personal details. I am still waiting on final approval to publish the server-side code.

I would like to personally thank the community for your comments, bug reports, and vulnerability disclosures. They all went into helping the development process.

The beta trial of this app has now ended and we've moved to the next phase of app development. It is our intention to publish the source code of future apps as the binaries are released to the public.

Once again, thank you for being part of this.

Terence Eden
Head of Open Technology - NHSX
