### ISSUE TITLE
Allow users to see infection statistics about their current location

### ISSUE THREAD

**Issue by ventisep** [nhsx/COVID-19-app-iOS-BETA#31]
**Describe the bug/improvement**
A potential improvement to the app to improve the number of people who download it would be to provide statisics of the current number of infections in the users area and so the current risk to the user of contracting Covid 19.  

Given that the app asks users to inform them if they have symptoms and this information is transmitted to the central server. The app could provide a report of the percentage of people who have reported symptoms in the users current vicinity in the last 10 days and the rate of increase  of reports in that vicinity  This could be used to provide a localised green, amber or red score for the area.

Such information would make the app more useful to people and so increase the liklihood of downloading it which makes it more effective.  It would also allow people to avoid riskier areas in real time which would itself lower the rates of infection in a hotspot.

Such a feature would require the app to send location information to the server when the user reports symptoms which would need approval but most people would agree to provide this if asked.

**Comment by tim-nhsx** [comment]
Thanks for raising this improvement request, although a difficult one to justify given our position on security and privacy, see here  - https://covid19.nhs.uk/privacy-and-data.html - "The app will not be able to track your location"

**Comment by lukeredpath** [comment]
Perhaps instead of deriving this information from data collected within the app could you use central government test data instead? I noticed that this data has recently been broken down to a fine grained level as reported in my local paper. 

I guess you could use the postcode to say “x people within this postcode area have self reported symptoms” too, or provide some kind of aggregate risk score based on both of the above points?

**Comment by ventisep** [comment]
Thanks I have read these.  I still think the functionality could work using data from only those who have developed symptoms and agreed to upload their data anonomously.  The statistics shared would only reveal the percentage of people who have reported symptoms in an area (and only if enough people are reporting symptoms to allow anonymity to be retained).  I think this could be covered under the position which does state:

“ If you develop coronavirus symptoms and choose to share the anonymous record on your phone with the NHS, this data will be stored in a secure database in the UK.

The NHS will then send an anonymous alert to app users who you came into significant contact with over the previous few days. This alert will not identify you in any way.

Why the app asks for your postcode

The NHS COVID-19 app only uses your postal district. This is the first part of your postcode, for example “PE12”. This generally contains about 8,000 addresses. It will not provide a precise location as to where you live.

We need your postal district to help the NHS:

use the app to predict and manage demand on local hospital services
**provide tailored advice to people living within a hotspot area if necessary**
improve the ‘contact risk model’ that determines which app users should be notified when an app user develops coronavirus symptoms”

I think this does allow for the idea of providing advice to people in a “hotspot” area.  To further deal with the concerns over privacy you could make this clear as part of the opt-in agreement when a person reports symptoms.

This is analogous to what people agree to do when they allow google maps to report their location and speed anonomously to identify traffic jams on busy roads.  I think most would agree to do this under an anonymous scheme such as the one your app allows for.

**Comment by ventisep** [comment]
I also agree with @lukeredpath other information currently shared could be used to enhance the appeal of the app

**Comment by ventisep** [comment]
Sorry accidently closed the issue while replying to @lukeredpath

**Comment by edent** [comment]
I'm pasting this message in every active GitHub issue, so you may receive duplicate notifications.

Today, I'm happy to announce that NHSX has released the full git commit history for the Isle of Wight Beta apps.

* Android - https://github.com/nhsx/COVID-19-app-Android-BETA
* iOS - https://github.com/nhsx/COVID-19-app-iOS-BETA

As discussed, we have redacted API keys, sensitive domain names, and some of the developers' personal details. I am still waiting on final approval to publish the server-side code.

I would like to personally thank the community for your comments, bug reports, and vulnerability disclosures. They all went into helping the development process.

The beta trial of this app has now ended and we've moved to the next phase of app development. It is our intention to publish the source code of future apps as the binaries are released to the public.

Once again, thank you for being part of this.

Terence Eden
Head of Open Technology - NHSX
