### ISSUE TITLE
Lack of Dark Blockchain support

### ISSUE THREAD

**Issue by GossiTheDog** [nhsx/COVID-19-app-iOS-BETA#9]

**Comment by tg12** [comment]
I’m really surprised about this too. +1. Not a whiff anywhere in the code about this. Shame.

**Comment by kraetos10** [comment]
Embarrasing they even considered this solution without dark blockchain support tbh.

**Comment by jeffalo** [comment]
no blockchain? what are they doing??

**Comment by adarrel753** [comment]
As far as I know the main use case for blockchain is when you have a document trail created by multiple parties and want each party to be able to verify that historic documents have not been altered after they have been added to the chain. I'm not sure how useful blockchain would be in a system when the data flow of the documents is always in one direction between two entities (i.e. device -> server). What am I missing?

**Comment by tg12** [comment]
> What am I missing?

Marketing Hype... and plus the fact it was a joke.

**Comment by kraetos10** [comment]
> What am I missing?

https://www.urbandictionary.com/define.php?term=Dark%20Blockchain

**Comment by adarrel753** [comment]
Oh! You got me!

**Comment by edent** [comment]
#WONTFIX
#POESLAW
